In [23]:
import pandas as pd
import numpy as np
from itertools import product

In [24]:
lookup_table = pd.read_csv('Fitness_value_magic04.csv', header=None).values.flatten()[:-1]

In [25]:
num_features = 10
combinations = np.array(list(product([0, 1], repeat=num_features)))[1:]
print(len(lookup_table))
print(combinations)

1023
[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 1]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]


In [26]:
def bitstring_to_index(features_used):
    index = -1 
    for i, bit in enumerate(reversed(features_used)):
        index += bit * (2 ** i) 
    return index
bitstring_to_index([0,0,0,0,0])

-1

In [27]:
def fitness_function(features_used):
    lookup_table_index = bitstring_to_index(features_used)
    accuracy = lookup_table[lookup_table_index]
    error = 1 - accuracy
    penalty_weight = 0.001
    fitness = error + penalty_weight * sum(features_used)
    return fitness

In [28]:
local_optima_list=[]
for current in combinations:
    local_optima = True
    for bit_flip in range(num_features):
        neighbor = list(current)
        neighbor[bit_flip] = 1 - neighbor[bit_flip]
        if sum(neighbor) != 0:
            index_neighbor = bitstring_to_index(neighbor)
            if fitness_function(current) > fitness_function(neighbor):
                local_optima = False
    if local_optima == True:
        local_optima_list.append(current)

In [29]:
print(len(local_optima_list))
local_optima_list

15


[array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1]),
 array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1]),
 array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1]),
 array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0]),
 array([1, 1, 1, 0, 1, 0, 0, 1, 1, 1]),
 array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0]),
 array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0]),
 array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0]),
 array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 1, 1, 1, 0]),
 array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0]),
 array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1]),
 array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0]),
 array([1, 1, 1, 1, 1, 1, 0, 0, 1, 0])]